FROM python:slim

# 필요한 패키지 설치
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libpq-dev ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# 필요한 파이썬 패키지 설치
COPY requirements.worker.txt ./
RUN pip install --no-cache-dir -r requirements.worker.txt
